# opa run -s -c config.yaml
services:
  - name: bundle-server
    url: http://localhost:8080/

bundles:
  bundle-server:
    service: bundle-server
    resource: bundles/bundle.tar.gz
    polling:
      #10 -> 10s gửi 1 lần, server hold rồi trả lời ngay khi có data
      long_polling_timeout_seconds: 10
      # min_delay_seconds: 5
      # max_delay_seconds: 10
